##name: CI
##
##on: [push]
#
## åœ¨ master åˆ†æ”¯å‘ç”Ÿ push äº‹ä»¶æ—¶è§¦å‘ã€‚
#on:
#   push:
#     branches:
#       - master
##
#env: # è®¾ç½®ç¯å¢ƒå˜é‡
# TZ: Asia/Shanghai # æ—¶åŒºï¼ˆè®¾ç½®æ—¶åŒºå¯ä½¿é¡µé¢ä¸­çš„ æœ€è¿‘æ›´æ–°æ—¶é—´ ä½¿ç”¨æ—¶åŒºæ—¶é—´ï¼‰
#
#jobs: # å·¥ä½œæµ
# build: # è‡ªå®šä¹‰åç§°
#   runs-on: ubuntu-latest # å¿…å¡«ï¼Œè¿è¡Œåœ¨è™šæ‹Ÿæœºç¯å¢ƒ ubuntu-latest
#
#   strategy:
#     matrix:
#       node-version: [14.x]
#
#   steps: # æ­¥éª¤1
#   - name: Push Matser To Gitee  # æ­¥éª¤4ï¼šGitHub å†…å®¹åŒæ­¥åˆ° Giteeï¼ŒåŒæ­¥ä»“åº“æ˜¯ master
#     uses: wearerequired/git-mirror-action@master
#     env:
#          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
#     with:  # ä»æºåˆ°ç›®çš„åœ°
#          source-repo: 'https://github.com/guqzhou/guqzhou.github.io.git'    #Github ä»“åº“åœ°å€
#          destination-repo: 'https://gitee.com/guqzhou/guqzhou.git'    #Gitee ä»“åº“åœ°å€
#   - name: Build Gitee Pages # æ­¥éª¤5ï¼šè‡ªåŠ¨éƒ¨ç½²åˆ° Gitee Pages
#     uses: yanglbme/gitee-pages-action@master
#     with:
#          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ç”¨æˆ·å
#          gitee-username: guqzhou
#          # æ³¨æ„åœ¨ Settings -> Secrets é…ç½® GITEE_PASSWORD
#          gitee-password: ${{ secrets.GITEE_PASSWORD }}
#          # æ³¨æ„æ›¿æ¢ä¸ºä½ çš„ Gitee ä»“åº“ï¼Œä»“åº“åä¸¥æ ¼åŒºåˆ†å¤§å°å†™ï¼Œè¯·å‡†ç¡®å¡«å†™ï¼Œå¦åˆ™ä¼šå‡ºé”™
#          gitee-repo: guqzhou/guqzhou
#          # è¦éƒ¨ç½²çš„åˆ†æ”¯ï¼Œé»˜è®¤æ˜¯ masterï¼Œè‹¥æ˜¯å…¶ä»–åˆ†æ”¯ï¼Œåˆ™éœ€è¦æŒ‡å®šï¼ˆæŒ‡å®šçš„åˆ†æ”¯å¿…é¡»å­˜åœ¨ï¼‰
#          branch: gh-pages
#
#
##      - name: Checkout # æ­¥éª¤1ï¼Œæ‹‰å–ä»£ç 
##      # ä½¿ç”¨çš„åŠ¨ä½œã€‚æ ¼å¼ï¼šuserName/repoNameã€‚ä½œç”¨ï¼šæ£€å‡ºä»“åº“ï¼Œè·å–æºç ã€‚ å®˜æ–¹actionsåº“ï¼šhttps://github.com/actions
##        uses: actions/checkout@v1
##
##      - name: Use Node.js ${{ matrix.node-version }} # æ­¥éª¤2
##        uses: actions/setup-node@v3
##        with:
##          node-version: ${{ matrix.node-version }}
#         # è®¾ç½®å‘åŒ… npm åœ°å€ä»“åº“
##         registry-url: https://registry.npmjs.org
##
###      - name: run deploy.sh # æ­¥éª¤3ï¼šæ‰§è¡Œè„šæœ¬ deploy.sh
###        env: # è®¾ç½®ç¯å¢ƒå˜é‡ï¼Œæœªè®¾ç½®åˆ™ä¸è¿è¡Œ
###           GITHUB_TOKEN: ${{ secrets.TOKEN }} # token
###           SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }} # ç§é’¥
###        run: npm install && npm run deploy  # æ‰§è¡Œ deploy.sh è„šæœ¬ï¼Œä½äºé¡¹ç›®æ ¹ç›®å½•
##
##      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
##        run: |
##          npm install
##          npm run build
###
##      - name: Deploy ğŸš€
##        uses: JamesIves/github-pages-deploy-action@4.1.5 # ä½œç”¨ï¼šå°†é¡¹ç›®æ„å»ºå’Œéƒ¨ç½²åˆ°githubã€‚ https://github.com/JamesIves/github-pages-deploy-action
##        with:
##          token: ${{ secrets.TKOEN }}
##          branch: gh-pages # The branch the action should deploy to.
##          folder: docs/.vuepress/dist # The folder the action should deploy.
##
#
#
#
#
##
